# Generated by Django 6.0.6 on 2026-06-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_extractedclause_riskflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
